"""add project_end_date

Revision ID: 5db6c97e5810
Revises: 122f43436109
Create Date: 2025-12-23 16:50:31.443269

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
import sqlmodel
import psycopg2


# revision identifiers, used by Alembic.
revision: str = '5db6c97e5810'
down_revision: Union[str, Sequence[str], None] = '122f43436109'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('quest', sa.Column('project_end_date', sa.DateTime(), nullable=True))
    op.drop_column('user', 'nickname')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('user', sa.Column('nickname', sa.VARCHAR(), nullable=True))
    op.drop_column('quest', 'project_end_date')
    # ### end Alembic commands ###
