"""remove_nickname_column

Revision ID: 92aae5fae736
Revises: 2f72e6564205
Create Date: 2025-12-11 13:30:45.676801

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
import sqlmodel
import psycopg2


# revision identifiers, used by Alembic.
revision: str = '92aae5fae736'
down_revision: Union[str, Sequence[str], None] = '2f72e6564205'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
