"""add deadline

Revision ID: 122f43436109
Revises: 8d83ea600f7e
Create Date: 2025-12-23 10:31:24.300587

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
import sqlmodel
import psycopg2


# revision identifiers, used by Alembic.
revision: str = '122f43436109'
down_revision: Union[str, Sequence[str], None] = '8d83ea600f7e'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('quest', sa.Column('start_date', sa.DateTime(), nullable=True))
    op.add_column('quest', sa.Column('deadline', sa.DateTime(), nullable=True))
    op.drop_column('quest', 'deadline_days')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('quest', sa.Column('deadline_days', sa.INTEGER(), nullable=False))
    op.drop_column('quest', 'deadline')
    op.drop_column('quest', 'start_date')
    # ### end Alembic commands ###
