"""add skills column

Revision ID: 1662638e8921
Revises: b049e3a44d8e
Create Date: 2025-12-22 17:11:10.114728

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
import sqlmodel
import psycopg2


# revision identifiers, used by Alembic.
revision: str = '1662638e8921'
down_revision: Union[str, Sequence[str], None] = 'b049e3a44d8e'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('user', sa.Column('skills', sqlmodel.sql.sqltypes.AutoString(), nullable=True))
    op.drop_column('user', 'nickname')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('user', sa.Column('nickname', sa.VARCHAR(), nullable=True))
    op.drop_column('user', 'skills')
    # ### end Alembic commands ###
