"""Add teamname column

Revision ID: c0c98fd460b1
Revises: 92aae5fae736
Create Date: 2025-12-15 11:15:46.019176

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
import sqlmodel
import psycopg2


# revision identifiers, used by Alembic.
revision: str = 'c0c98fd460b1'
down_revision: Union[str, Sequence[str], None] = '92aae5fae736'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('user', sa.Column('team_name', sqlmodel.sql.sqltypes.AutoString(), nullable=True))
    op.drop_column('user', 'is_assessed')
    op.drop_column('user', 'nickname')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('user', sa.Column('nickname', sa.VARCHAR(), nullable=True))
    op.add_column('user', sa.Column('is_assessed', sa.BOOLEAN(), nullable=False))
    op.drop_column('user', 'team_name')
    # ### end Alembic commands ###
