"""update database

Revision ID: b049e3a44d8e
Revises: c0c98fd460b1
Create Date: 2025-12-17 17:14:45.870949

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
import sqlmodel
import psycopg2


# revision identifiers, used by Alembic.
revision: str = 'b049e3a44d8e'
down_revision: Union[str, Sequence[str], None] = 'c0c98fd460b1'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
